name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # There is no "allow failures" option for GitHub Actions, but we test on
        # the latest LTS release anyway just so we can notice if it breaks.
        #
        #
        # Version 0.6.0 is the one we declare as the minimum in package.json.
        # This one may not work because it precedes what `uglify-js` declares
        # support for.
        #
        # Version 0.8.0 is the one the `uglify-js` package declares as the
        # minimum in its package.json. This is likely the earliest one we have
        # confidence in supporting, though we probably won't support it for long
        # if any issues come up.
        #
        # Version 16 is a recent version, and we intend to fully support it.
        #
        # Version 17 is the latest major version as of this writing. We intend
        # to support it, but we may not reasonably be able to if it introduces
        # regressions.
        #
        node-version: ["0.6.0", "0.8.0", "16", "17", "lts/*"]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
      - name: Check the Node.js version
        run: node --version
      - name: Install npm dependencies
        run: npm install
      - name: Run unit tests
        run: npm test
